/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab3_5;

import javax.swing.JOptionPane;

/**
 *
 * @author sovas
 */
public class BookDialog extends javax.swing.JDialog {

    private LibraryForm libraryForm;
    private LibraryDAO libraryDAO;
    private Book previousBook = null;
    private boolean updateMode = false;

    /**
     * Creates new form BookDialog
     */
    public BookDialog(LibraryForm theLibraryForm, LibraryDAO theLibraryDAO) {
        initComponents();
        libraryForm = theLibraryForm;
        libraryDAO = theLibraryDAO;
    }

    public BookDialog(LibraryForm theLibraryForm,
            LibraryDAO theLibraryDAO, Book thePreviousBook, boolean theUpdateMode) {
        initComponents();

        libraryForm = theLibraryForm;
        libraryDAO = theLibraryDAO;
        previousBook = thePreviousBook;

        updateMode = theUpdateMode;

        if (updateMode) {
            setTitle("Update Book");

            populateGui(previousBook);
        }
    }

    private void populateGui(Book theBook) {

        bookNameField.setText(theBook.getName());
        bookAuthorField.setText(theBook.getAuthor());
        bookGenreField.setText(theBook.getGenre());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        bookNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bookAuthorField = new javax.swing.JTextField();
        bookGenreField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adding a book");
        setResizable(false);

        jLabel3.setText("Genre");

        jLabel1.setText("Name");

        jLabel2.setText("Author");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addGap(51, 51, 51)
                        .addComponent(cancelButton))
                    .addComponent(bookAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookGenreField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookGenreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        addBook();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    protected void addBook() {

        String name = bookNameField.getText();
        String author = bookAuthorField.getText();
        String genre = bookGenreField.getText();

        Book tempBook = null;

        if (updateMode) {
            tempBook = previousBook;

            tempBook.setName(name);
            tempBook.setAuthor(author);
            tempBook.setGenre(genre);
        } else {
            tempBook = new Book(name, author, genre);
        }

        try {
            if (updateMode) {
                libraryDAO.updateBook(tempBook);
            } else {
                libraryDAO.addBook(tempBook);
            }

            setVisible(false);
            dispose();

            libraryForm.refreshBooksView();

            JOptionPane.showMessageDialog(libraryForm,
                    "Book saved succesfully.", "Book Saved",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(libraryForm,
                    "Error saving book: " + exc.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookAuthorField;
    private javax.swing.JTextField bookGenreField;
    private javax.swing.JTextField bookNameField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

}
